"""empty message

Revision ID: 84065f3d33e7
Revises: eecd1a60e2d5
Create Date: 2024-08-04 17:19:09.702655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84065f3d33e7'
down_revision = 'eecd1a60e2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('line_test_number_of_border_touches', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    op.add_column('patients', sa.Column('line_test_number_of_beyond_border', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    op.add_column('patients', sa.Column('psychometric_index_PE', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'psychometric_index_PE')
    op.drop_column('patients', 'line_test_number_of_beyond_border')
    op.drop_column('patients', 'line_test_number_of_border_touches')
    # ### end Alembic commands ###
